id: I23797124
ocr_import_info:
  timestamp: '2023-04-04T11:39:29.385781+00:00'
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.8
  sponsor: Atisha
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.2
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-04-04 11:54:17.631292+00:00
last_modified: 2023-04-04 11:54:17.631299+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC401
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC401
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་འགྲེལ་བཤད།
  languages:
  - bo
  author: པཎྜི་ཏ་ཛ་ཡ་ཨ་ནནྟ།
statistics:
  ocr_word_mean_confidence_index: 0.9990945859052169
  ocr_word_median_confidence_index: 1.0
bases:
  I2PD18649:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18649
      total_pages: 782
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18649.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9990945859052169
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
